spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      maximum-pool-size: 5
#    open-in-view: false

management:
  endpoint:
    web:
      exposure:
        include: info,health
